/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type EventUpdateVestingEscrowRecipient = {
  escrow: Address;
  oldRecipient: Address;
  newRecipient: Address;
  signer: Address;
};

export type EventUpdateVestingEscrowRecipientArgs =
  EventUpdateVestingEscrowRecipient;

export function getEventUpdateVestingEscrowRecipientEncoder(): Encoder<EventUpdateVestingEscrowRecipientArgs> {
  return getStructEncoder([
    ['escrow', getAddressEncoder()],
    ['oldRecipient', getAddressEncoder()],
    ['newRecipient', getAddressEncoder()],
    ['signer', getAddressEncoder()],
  ]);
}

export function getEventUpdateVestingEscrowRecipientDecoder(): Decoder<EventUpdateVestingEscrowRecipient> {
  return getStructDecoder([
    ['escrow', getAddressDecoder()],
    ['oldRecipient', getAddressDecoder()],
    ['newRecipient', getAddressDecoder()],
    ['signer', getAddressDecoder()],
  ]);
}

export function getEventUpdateVestingEscrowRecipientCodec(): Codec<
  EventUpdateVestingEscrowRecipientArgs,
  EventUpdateVestingEscrowRecipient
> {
  return combineCodec(
    getEventUpdateVestingEscrowRecipientEncoder(),
    getEventUpdateVestingEscrowRecipientDecoder()
  );
}
