/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from '@solana/web3.js';

export type EventCreateRootEscrow = {
  rootEscrow: Address;
  maxClaimAmount: bigint;
  maxEscrow: bigint;
  version: bigint;
  root: ReadonlyUint8Array;
};

export type EventCreateRootEscrowArgs = {
  rootEscrow: Address;
  maxClaimAmount: number | bigint;
  maxEscrow: number | bigint;
  version: number | bigint;
  root: ReadonlyUint8Array;
};

export function getEventCreateRootEscrowEncoder(): Encoder<EventCreateRootEscrowArgs> {
  return getStructEncoder([
    ['rootEscrow', getAddressEncoder()],
    ['maxClaimAmount', getU64Encoder()],
    ['maxEscrow', getU64Encoder()],
    ['version', getU64Encoder()],
    ['root', fixEncoderSize(getBytesEncoder(), 32)],
  ]);
}

export function getEventCreateRootEscrowDecoder(): Decoder<EventCreateRootEscrow> {
  return getStructDecoder([
    ['rootEscrow', getAddressDecoder()],
    ['maxClaimAmount', getU64Decoder()],
    ['maxEscrow', getU64Decoder()],
    ['version', getU64Decoder()],
    ['root', fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getEventCreateRootEscrowCodec(): Codec<
  EventCreateRootEscrowArgs,
  EventCreateRootEscrow
> {
  return combineCodec(
    getEventCreateRootEscrowEncoder(),
    getEventCreateRootEscrowDecoder()
  );
}
