/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type EventCloseClaimStatus = {
  escrow: Address;
  recipient: Address;
  rentReceiver: Address;
};

export type EventCloseClaimStatusArgs = EventCloseClaimStatus;

export function getEventCloseClaimStatusEncoder(): Encoder<EventCloseClaimStatusArgs> {
  return getStructEncoder([
    ['escrow', getAddressEncoder()],
    ['recipient', getAddressEncoder()],
    ['rentReceiver', getAddressEncoder()],
  ]);
}

export function getEventCloseClaimStatusDecoder(): Decoder<EventCloseClaimStatus> {
  return getStructDecoder([
    ['escrow', getAddressDecoder()],
    ['recipient', getAddressDecoder()],
    ['rentReceiver', getAddressDecoder()],
  ]);
}

export function getEventCloseClaimStatusCodec(): Codec<
  EventCloseClaimStatusArgs,
  EventCloseClaimStatus
> {
  return combineCodec(
    getEventCloseClaimStatusEncoder(),
    getEventCloseClaimStatusDecoder()
  );
}
