/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type EventCloseVestingEscrow = { escrow: Address };

export type EventCloseVestingEscrowArgs = EventCloseVestingEscrow;

export function getEventCloseVestingEscrowEncoder(): Encoder<EventCloseVestingEscrowArgs> {
  return getStructEncoder([['escrow', getAddressEncoder()]]);
}

export function getEventCloseVestingEscrowDecoder(): Decoder<EventCloseVestingEscrow> {
  return getStructDecoder([['escrow', getAddressDecoder()]]);
}

export function getEventCloseVestingEscrowCodec(): Codec<
  EventCloseVestingEscrowArgs,
  EventCloseVestingEscrow
> {
  return combineCodec(
    getEventCloseVestingEscrowEncoder(),
    getEventCloseVestingEscrowDecoder()
  );
}
