/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type EventFundRootEscrow = { rootEscrow: Address; fundedAmount: bigint };

export type EventFundRootEscrowArgs = {
  rootEscrow: Address;
  fundedAmount: number | bigint;
};

export function getEventFundRootEscrowEncoder(): Encoder<EventFundRootEscrowArgs> {
  return getStructEncoder([
    ['rootEscrow', getAddressEncoder()],
    ['fundedAmount', getU64Encoder()],
  ]);
}

export function getEventFundRootEscrowDecoder(): Decoder<EventFundRootEscrow> {
  return getStructDecoder([
    ['rootEscrow', getAddressDecoder()],
    ['fundedAmount', getU64Decoder()],
  ]);
}

export function getEventFundRootEscrowCodec(): Codec<
  EventFundRootEscrowArgs,
  EventFundRootEscrow
> {
  return combineCodec(
    getEventFundRootEscrowEncoder(),
    getEventFundRootEscrowDecoder()
  );
}
