/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type EventClaim = { amount: bigint; currentTs: bigint; escrow: Address };

export type EventClaimArgs = {
  amount: number | bigint;
  currentTs: number | bigint;
  escrow: Address;
};

export function getEventClaimEncoder(): Encoder<EventClaimArgs> {
  return getStructEncoder([
    ['amount', getU64Encoder()],
    ['currentTs', getU64Encoder()],
    ['escrow', getAddressEncoder()],
  ]);
}

export function getEventClaimDecoder(): Decoder<EventClaim> {
  return getStructDecoder([
    ['amount', getU64Decoder()],
    ['currentTs', getU64Decoder()],
    ['escrow', getAddressDecoder()],
  ]);
}

export function getEventClaimCodec(): Codec<EventClaimArgs, EventClaim> {
  return combineCodec(getEventClaimEncoder(), getEventClaimDecoder());
}
