/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type EventClaimV3 = {
  amount: bigint;
  currentTs: bigint;
  escrow: Address;
  vestingStartTime: bigint;
  cliffTime: bigint;
  frequency: bigint;
  cliffUnlockAmount: bigint;
  amountPerPeriod: bigint;
  numberOfPeriod: bigint;
  recipient: Address;
};

export type EventClaimV3Args = {
  amount: number | bigint;
  currentTs: number | bigint;
  escrow: Address;
  vestingStartTime: number | bigint;
  cliffTime: number | bigint;
  frequency: number | bigint;
  cliffUnlockAmount: number | bigint;
  amountPerPeriod: number | bigint;
  numberOfPeriod: number | bigint;
  recipient: Address;
};

export function getEventClaimV3Encoder(): Encoder<EventClaimV3Args> {
  return getStructEncoder([
    ['amount', getU64Encoder()],
    ['currentTs', getU64Encoder()],
    ['escrow', getAddressEncoder()],
    ['vestingStartTime', getU64Encoder()],
    ['cliffTime', getU64Encoder()],
    ['frequency', getU64Encoder()],
    ['cliffUnlockAmount', getU64Encoder()],
    ['amountPerPeriod', getU64Encoder()],
    ['numberOfPeriod', getU64Encoder()],
    ['recipient', getAddressEncoder()],
  ]);
}

export function getEventClaimV3Decoder(): Decoder<EventClaimV3> {
  return getStructDecoder([
    ['amount', getU64Decoder()],
    ['currentTs', getU64Decoder()],
    ['escrow', getAddressDecoder()],
    ['vestingStartTime', getU64Decoder()],
    ['cliffTime', getU64Decoder()],
    ['frequency', getU64Decoder()],
    ['cliffUnlockAmount', getU64Decoder()],
    ['amountPerPeriod', getU64Decoder()],
    ['numberOfPeriod', getU64Decoder()],
    ['recipient', getAddressDecoder()],
  ]);
}

export function getEventClaimV3Codec(): Codec<EventClaimV3Args, EventClaimV3> {
  return combineCodec(getEventClaimV3Encoder(), getEventClaimV3Decoder());
}
