/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type EventCancelVestingEscrow = {
  escrow: Address;
  signer: Address;
  claimableAmount: bigint;
  remainingAmount: bigint;
  cancelledAt: bigint;
};

export type EventCancelVestingEscrowArgs = {
  escrow: Address;
  signer: Address;
  claimableAmount: number | bigint;
  remainingAmount: number | bigint;
  cancelledAt: number | bigint;
};

export function getEventCancelVestingEscrowEncoder(): Encoder<EventCancelVestingEscrowArgs> {
  return getStructEncoder([
    ['escrow', getAddressEncoder()],
    ['signer', getAddressEncoder()],
    ['claimableAmount', getU64Encoder()],
    ['remainingAmount', getU64Encoder()],
    ['cancelledAt', getU64Encoder()],
  ]);
}

export function getEventCancelVestingEscrowDecoder(): Decoder<EventCancelVestingEscrow> {
  return getStructDecoder([
    ['escrow', getAddressDecoder()],
    ['signer', getAddressDecoder()],
    ['claimableAmount', getU64Decoder()],
    ['remainingAmount', getU64Decoder()],
    ['cancelledAt', getU64Decoder()],
  ]);
}

export function getEventCancelVestingEscrowCodec(): Codec<
  EventCancelVestingEscrowArgs,
  EventCancelVestingEscrow
> {
  return combineCodec(
    getEventCancelVestingEscrowEncoder(),
    getEventCancelVestingEscrowDecoder()
  );
}
